
#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/lang/XTypeProvider.idl>

/*

	http://wiki.services.openoffice.org/wiki/IDL_Files_and_Cpp
	http://wiki.services.openoffice.org/wiki/IDL_Files_and_Cpp#Specifying_an_interface

 */

module br { module com { module bb {

   /**
     * Interface to lib3270.
     */
    interface I3270 : com::sun::star::uno::XInterface
    {
		string	getVersion();

        short	Connect( [in] string hostinfo );
        short 	Disconnect();
        short	getConnectionState();

        string	getScreenContentAt([in] short row, [in] short col, [in] short size);
        string	getScreenContent();
        short	waitForScreen([in] short timeout);
        short	waitForStringAt([in] short row, [in] short col, [in] string key, [in] short timeout);

		short	sendEnterKey();
		short 	setStringAt([in] short row, [in] short col, [in] string str);

        /*

        setToggle()
        getToggle()

		getCursorRow()
		getCursorCol()

		setCursorPosition()

		sendPFKey()

        */

    };

    service g3270
    {
        // exported interfaces:
        interface I3270;
    };

}; }; };

