#ifndef CONFIG_H_INCLUDED

	#define CONFIG_H_INCLUDED 1

	#define PACKAGE_NAME "g3270"
	#define PACKAGE_VERSION "3.3.7p5"
	#define GETTEXT_PACKAGE "g3270"
	#define LOCALEDIR "mo"

#endif /* CONFIG_H_INCLUDED */
