
#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/lang/XTypeProvider.idl>

/*

	http://wiki.services.openoffice.org/wiki/IDL_Files_and_Cpp
	http://wiki.services.openoffice.org/wiki/IDL_Files_and_Cpp#Specifying_an_interface

 */

module br { module com { module bb {

   /**
     * Interface to lib3270.
     *
     * http://wiki.services.openoffice.org/wiki/Documentation/DevGuide/ProUNO/Bridge/Default_Mappings
     *
     */
    interface pw3270 : com::sun::star::uno::XInterface
    {
		string	getVersion();

        short	Connect( [in] string hostinfo, [in] short wait );
        short 	Disconnect();
        short	getConnectionState();
		boolean isConnected();
		boolean isTerminalReady();
		short	waitForEvents();
		short	waitForTerminalReady([in] short timeout);

        string	getScreenContentAt([in] short row, [in] short col, [in] short size);
        string	getScreenContent();
        short	waitForReset([in] short timeout);
        short	waitForStringAt([in] short row, [in] short col, [in] string key, [in] short timeout);
		boolean	queryStringAt([in] short row, [in] short col, [in] string key);

		short	sendEnterKey();
		short 	setStringAt([in] short row, [in] short col, [in] string str);
		short	sendPFKey([in] short key);

    };

    service srv3270
    {
        // exported interfaces:
        interface pw3270;
    };

}; }; };

